FROM justdnaseq/sambamba:1.0.1 AS sambamba
FROM quay.io/biocontainers/minimap2:2.30--h577a1d6_0

COPY --from=sambamba /usr/local/bin/sambamba /usr/local/bin/sambamba
COPY --from=sambamba /lib/x86_64-linux-gnu/libz.so.1 /lib/x86_64-linux-gnu/libz.so.1
COPY --from=sambamba /lib/x86_64-linux-gnu/liblz4.so.1 /lib/x86_64-linux-gnu/liblz4.so.1
